[versions]
coroutines = "1.6.4"
dokka = "1.5.31"

[libraries]
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
